### PR TITLE
Mark Cypher first usage on every page

### PR DESCRIPTION
**Pull request by recrwplay**
Add the `mark-terms` extension to mark the first instance of Cypher on every page.

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-cypher-549.surge.sh

**Comment by davidoliverSP2** [comment]
Nice

Is there a way for it to ignore headers? it looks a little odd in the navigation

Screenshot 2023-05-12 at 11 50 58

**Comment by recrwplay** [comment]
> Is there a way for it to ignore headers? it looks a little odd in the navigation

Yes, or with a ui-bundle update we should be able to hide them from view when titles are used in navigation.

**Comment by recrwplay** [comment]
I've updated the extension so that in version 1.1.0 you can specify whether to mark or ignore titles (and it also recognises list items). This PR now builds without marking usage in titles.

**Review by davidoliverSP2 — APPROVED** [review]
Great stuff, thanks @recrwplay 👍

**Pull request merged**
