### PR TITLE
Add NODES 23 ad

### PR DESCRIPTION
**Pull request by recrwplay**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-cypher-561.surge.sh

**Comment by davidoliverSP2** [comment]
@recrwplay the surge link (+ local builds) doesn't pick up the ad - should it? (could this PR depend on another in in the UI repo?)

**Comment by recrwplay** [comment]
I added it to the `publish.yml` playbook only, and the checks here use `preview.yml`. You could test it locally by building with the publish playbook, but you'd also need to update the source branches in that playbook, replacing `5.x` with `HEAD`

**Review by davidoliverSP2 — APPROVED** [review]
Looks good, thanks @recrwplay 👍 

Lets add a reminder to remove this on the 27th Oct!

**Pull request merged**
