### PR TITLE
Document OPTIONAL CALL

### PR DESCRIPTION
**Pull request by JPryce-Aklundh**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1034.surge.sh

Updated pages:
- [CALL procedure](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/clauses/call)
- [Deprecations, additions, and compatibility](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/deprecations-additions-removals-compatibility)
- [CALL subqueries](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/subqueries/call-subquery)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1034.surge.sh

Updated pages:
- [CALL procedure](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/clauses/call)
- [Deprecations, additions, and compatibility](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/deprecations-additions-removals-compatibility)
- [CALL subqueries](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/subqueries/call-subquery)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1034.surge.sh

Updated pages:
- [CALL procedure](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/clauses/call)
- [Deprecations, additions, and compatibility](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/deprecations-additions-removals-compatibility)
- [CALL subqueries](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/subqueries/call-subquery)

**Review by JoelBergstrand — APPROVED** [review]
Great cleanup of the call procedure page!

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1034.surge.sh

Updated pages:
- [CALL procedure](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/clauses/call)
- [Deprecations, additions, and compatibility](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/deprecations-additions-removals-compatibility)
- [CALL subqueries](https://neo4j-docs-cypher-1034.surge.sh/cypher-manual/5/subqueries/call-subquery)

**Review by loveleif — APPROVED** [review]
Sorry for the delay! Great work! Thanks.

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
