### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by juantoser**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1110.surge.sh

Updated pages:
- [CALL subqueries in transactions](https://neo4j-docs-cypher-1110.surge.sh/cypher-manual/5/subqueries/subqueries-in-transactions)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1110.surge.sh

Updated pages:
- [CALL subqueries in transactions](https://neo4j-docs-cypher-1110.surge.sh/cypher-manual/5/subqueries/subqueries-in-transactions)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Comment by JPryce-Aklundh** [comment]
Thank you @juantoser

**Pull request merged**
