### PR TITLE
Update Parallel runtime example query plan

### PR DESCRIPTION
**Pull request by JPryce-Aklundh**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-860.surge.sh

Updated pages:
- [Runtime concepts](https://neo4j-docs-cypher-860.surge.sh/cypher-manual/5/planning-and-tuning/runtimes/concepts)

**Review by pontusmelke — APPROVED** [review]
Looks good! 

Do you think we should mention the partitioned scan in the section below that starts with `A key difference...`? Maybe something saying, "another difference is that when possible we use partitioned operators. Partitioned operators partition the data in different segments and operates on each segment in parallel" (or something like that)?

**Comment by JPryce-Aklundh** [comment]
Sounds good - I'll review your PR about partitioned operators now, and then add something to this PR

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-860.surge.sh

Updated pages:
- [Runtime concepts](https://neo4j-docs-cypher-860.surge.sh/cypher-manual/5/planning-and-tuning/runtimes/concepts)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-860.surge.sh

Updated pages:
- [Runtime concepts](https://neo4j-docs-cypher-860.surge.sh/cypher-manual/5/planning-and-tuning/runtimes/concepts)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
