### PR TITLE
Add token privilege notes

### PR DESCRIPTION
**Pull request by JPryce-Aklundh**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1015.surge.sh

Updated pages:
- [Database administration](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/database-administration)
- [Managing privileges](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/manage-privileges)
- [Write privileges](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/privileges-writes)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-1015.surge.sh

Updated pages:
- [Database administration](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/database-administration)
- [Managing privileges](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/manage-privileges)
- [Write privileges](https://neo4j-docs-cypher-1015.surge.sh/cypher-manual/4.4/administration/access-control/privileges-writes)

**Review by renetapopova — APPROVED** [review]
Looks good to me.

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
