### PR TITLE
Update `SHOW SETTINGS` output after bug fix

### PR DESCRIPTION
**Pull request by Hunterness**
changing the `"No Value"` to `null` when value, default value or startup value is not set

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by l-heemann — APPROVED** [review]
lgtm, thanks for looking into this.

Not sure why the build breaks though? 🤔

**Comment by Hunterness** [comment]
> Not sure why the build breaks though? 🤔

The show settings tests are broken somehow, not sure why 🤷 I was hoping this would have helped but sadly not :(

**Review by AlexicaWright — APPROVED** [review]
👍

**Pull request merged**
