### PR TITLE
add property rules syntax to keyword glossary

### PR DESCRIPTION
**Pull request by HannesSandberg**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by Hunterness — APPROVED** [review]
We said we left it out of additions/deprecations/removals chapter for now since it's not yet publicly available if I remember correctly.

And I think your check with the docs team yielded only update operations manual privilege chapter.

Based on those assumptions I'll approve this, if any of them is false I guess you know what to do XD

**Comment by HannesSandberg** [comment]
> We said we left it out of additions/deprecations/removals chapter for now since it's not yet publicly available if I remember correctly.

> And I think your check with the docs team yielded only update operations manual privilege chapter.

Yes, that is correct

**Comment by HannesSandberg** [comment]
Closed this PR since this page is being removed and will reference the cheat sheet instead.

**Comment by Hunterness** [comment]
> and will reference the cheat sheet instead.

So then we definitely should have a cheat sheet example for each of the privileges XD (which you did add already)

**Pull request closed without merging**
