### PR TITLE
Add descriptions of partitioned operators.

### PR DESCRIPTION
**Pull request by pontusmelke**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-cypher-847.surge.sh

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-847.surge.sh

Updated pages:
- [Operators](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators)
- [Operators in detail](https://neo4j-docs-cypher-847.surge.sh/cypher-manual/5/planning-and-tuning/operators/operators-detail)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by JPryce-Aklundh — APPROVED** [review]

**Pull request merged**
