### PR TITLE
FTP URL example for LOAD CSV

### PR DESCRIPTION
**Pull request by rsill-neo4j**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-940.surge.sh

Updated pages:
- [LOAD CSV](https://neo4j-docs-cypher-940.surge.sh/cypher-manual/5/clauses/load-csv)

**Review by JPryce-Aklundh — COMMENTED** [review]
Thanks @rsill-neo4j - I think we should make explicit in the example header (and somewhere in the example) that it also shows how to use LOAD CSV with authentication.

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-940.surge.sh

Updated pages:
- [LOAD CSV](https://neo4j-docs-cypher-940.surge.sh/cypher-manual/5/clauses/load-csv)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-cypher-940.surge.sh

Updated pages:
- [LOAD CSV](https://neo4j-docs-cypher-940.surge.sh/cypher-manual/5/clauses/load-csv)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by JPryce-Aklundh — APPROVED** [review]

**Pull request merged**
